# Generated by Django 2.2.4 on 2019-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='titlename',
            field=models.CharField(max_length=100),
        ),
    ]
