# Generated by Django 2.2.4 on 2019-08-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_auto_20190823_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='titlename',
            new_name='title',
        ),
    ]
